# -*- coding: utf-8 -*-
"""Forcasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yeQenVy-iKrREDBZ2v0NK0x_o2M4nlh
"""



"""LOad and Inspect Data"""

import pandas as pd
import numpy as np
import math
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

carsales = pd.read_csv('carsales.csv')
print(carsales.head())

"""Clean Data and Create Time Variable"""

carsales.columns = ['month', 'sales']
carsales = carsales.loc[0:107, :].copy()
carsales['period'] = list(range(108))
print(carsales.tail())

"""Visualize Sales Trend"""

plt.scatter(carsales['period'], carsales['sales'])
plt.title('Car Sales by Month')
plt.xlabel('Month (Period)')
plt.ylabel('Sales')
plt.show()

"""Fit Linear Regression Model"""

X = carsales[['period']]
y = carsales['sales']

regressor = LinearRegression()
regressor.fit(X, y)

print("Slope:", regressor.coef_[0])
print("Intercept:", regressor.intercept_)

predicted = regressor.predict(X)

plt.scatter(carsales['period'], carsales['sales'])
plt.plot(carsales['period'], predicted, color='red')
plt.title('Regression Line')
plt.xlabel('Month')
plt.ylabel('Sales')
plt.show()

"""Compare Regression vs Hypothesized Line"""

plt.scatter(carsales['period'], carsales['sales'])
plt.plot(carsales['period'], predicted, 'r-', label='Regression')
plt.plot(carsales['period'],
         [125 * i + 8000 for i in carsales['period']],
         'r--', label='Hypothesized')

plt.legend()
plt.show()

"""Calculate model errors"""

saleslist = carsales['sales'].tolist()
regressionline = regressor.predict(X)
hypothesizedline = [125 * i + 8000 for i in carsales['period']]

error1 = [(x - y) for x, y in zip(regressionline, saleslist)]
error2 = [(x - y) for x, y in zip(hypothesizedline, saleslist)]

error1abs = [abs(val) for val in error1]
error2abs = [abs(val) for val in error2]

print("MAE Regression:", np.mean(error1abs))
print("MAE Hypothesized:", np.mean(error2abs))

error1sq = [val**2 for val in error1]
error2sq = [val**2 for val in error2]

print("RMSE Regression:", np.sqrt(np.mean(error1sq)))
print("RMSE Hypothesized:", np.sqrt(np.mean(error2sq)))

def get_rmse(line, actual):
    error = [(x - y) for x, y in zip(line, actual)]
    errorsquared = [(value)**2 for value in error]
    return np.sqrt(np.mean(errorsquared))

"""Forcast Future sales"""

x_extended = np.append(carsales['period'], np.arange(108, 116))
x_extended = x_extended.reshape(-1, 1)

extended_prediction = regressor.predict(x_extended)

plt.scatter(carsales['period'], carsales['sales'])
plt.plot(x_extended, extended_prediction, 'r--')
plt.show()

"""Multivariate Regression"""

carsales['quadratic'] = carsales['period']**2
carsales['cubic'] = carsales['period']**3

x3 = carsales[['period','quadratic','cubic']].values
y2 = carsales['sales'].values.reshape(-1,1)

regressor_cubic = LinearRegression()
regressor_cubic.fit(x3, y2)

plt.scatter(carsales['period'], carsales['sales'])
plt.plot(X, regressor.predict(X), 'r-', label='Linear')
plt.plot(carsales['period'], regressor_cubic.predict(x3), 'r--', label='Cubic')
plt.legend()
plt.show()

"""Trigonometric regression"""

carsales['sin_period'] = np.sin(carsales['period'] * 2 * np.pi / 12)
carsales['cos_period'] = np.cos(carsales['period'] * 2 * np.pi / 12)

x_trig = carsales[['period','sin_period','cos_period']].values
y3 = carsales['sales'].values.reshape(-1,1)

regressor_trig = LinearRegression()
regressor_trig.fit(x_trig, y3)

plt.plot(carsales['period'], carsales['sales'])
plt.plot(carsales['period'], regressor_trig.predict(x_trig), 'r--')
plt.show()

trig_line = regressor_trig.predict(x_trig)[:,0]
print("Trig RMSE:", get_rmse(trig_line, saleslist))

"""More complex regression model"""

carsales['sqrt'] = np.sqrt(carsales['period'])
carsales['log'] = np.log(carsales['period'] + 1)

x_complex = carsales[['period','log','sin_period','cos_period',
                      'sqrt','quadratic','cubic']].values

y4 = carsales['sales'].values.reshape(-1,1)

regressor_complex = LinearRegression()
regressor_complex.fit(x_complex, y4)

complex_line = regressor_complex.predict(x_complex).flatten()

print("Complex RMSE:", get_rmse(complex_line, saleslist))

"""Test split and model evaluation"""

x_train = carsales.loc[0:80, ['period']].values
x_test = carsales.loc[81:107, ['period']].values

x_trig_train = carsales.loc[0:80, ['period','sin_period','cos_period']].values
x_trig_test = carsales.loc[81:107, ['period','sin_period','cos_period']].values

y_train = carsales.loc[0:80, 'sales'].values.reshape(-1,1)
y_test = carsales.loc[81:107, 'sales'].values.reshape(-1,1)

regressor.fit(x_train, y_train)
regressor_trig.fit(x_trig_train, y_train)

test_pred = regressor.predict(x_test).flatten()
trig_pred = regressor_trig.predict(x_trig_test).flatten()

print("Linear Test RMSE:", get_rmse(test_pred, saleslist[81:108]))
print("Trig Test RMSE:", get_rmse(trig_pred, saleslist[81:108]))

"""Final Forecast"""

future_period = 108
future_sin = math.sin(future_period * 2 * math.pi / 12)
future_cos = math.cos(future_period * 2 * math.pi / 12)

next_input = np.array([[future_period, future_sin, future_cos]])
forecast = regressor_trig.predict(next_input)

print("Next Month Forecast:", forecast[0][0])