# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xg32vPuyX8ZTH0G5eZHRm4YwWWUh9Brj

**Problem 1**. define fair as having an expected value of $0$ (zero).Probability of rolling a $7$ is $\frac{6}{36} = \frac{1}{6}$. The expected value $(4 \cdot \frac {1}{6} - 1 \cdot \ \frac{5}{6}) = \frac{4}{5} - \frac{5}{6} = -\frac{1}{6}$. Not fair. Fair would be with 5 instead of 4 for a win

**Problem 1** Define fair as having an expected value if $0$. Probability of rolling a $7$ is $\frac{6}{36} = \frac{1}{6}$. The expected value $(4 \cdot \frac{1}{6} - 1 \cdot \frac{5}{6}) = \frac{4}{5} - \frac{5}{6} = -\frac{1}{6}$. Not fair. Fair would be with $5$ instead of $4$ for a win
"""

import random
times = 1000000
money = 0

for i in range(times):
  d1 = random.randint(1,6)
  d2 = random.randint(1,6)
  sum = d1 + d2
  if sum == 7:
    money += 5
  else:
    money -= 1
    print(money/)

"""**Problem 2** There are 216 total possible outcomes when rolling 3 dice, by counting all outcomes whose sum is not a prime number and deviding by 216, the probability the sum is not prome is .662. The simulation estimates the probability by randomly rolling three dice many times and recording how often the sum is not a prime number. The output is close to 0.662, which matches the exact probability found by counting all possible outcomes. This shows that about 66% of the time, the sum of three dice is not prime. As the number of simulations increases, the simulated probability gets closer to the theoretical value."""

count = 0

for d1 in range(1,7):
  for d2 in range(1,7):
    for d3 in range(1,7):
      sum = d1 + d2 + d3
      if sum not in [3,5,7,11,13,17]:
        count += 1
      else:
        pass

print(count/(6*6*6))

lockers = [' '] * 100
for student in range(100):
  for locker in range (len(lockers)):
    if (locker+1) % (student+1) ==0:
      if lockers[locker] == ' ': #if lockers is closed
        lockers[locker] = '*' #open it
      else:
        lockers[locker] = ' ' #otherwise close the door
  print(''.join(lockers))