# -*- coding: utf-8 -*-
"""Lab_06_Notebook_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXf80uVrelY_sQVCdNRIpJ_jdeSEre8k

Basic Matplotlib Plots

 The chapter uses line plots to graph probability distributions and histograms to visualize sampled data distributions. These plots help us see centrality, spread, and how probabilities are distributed.
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

"""A line plot is used to show how probability chages across possible head counts"""

num_flips = 20
prob_head = 0.5
x_values = range(num_flips + 1)
y_values = stats.binom.pmf(x_values, num_flips, prob_head)

plt.plot(x_values, y_values)
plt.xlabel('Head-count')
plt.ylabel('Probability')
plt.title('Line Plot of Binomial Probabilities')
plt.show()

"""you can compare several distrubutuions by plotting multiple lines together"""

num_flips = 20
prob_head = 0.5
x_values = range(num_flips + 1)
y_values = stats.binom.pmf(x_values, num_flips, prob_head)

plt.plot(x_values, y_values)
plt.xlabel('Head-count')
plt.ylabel('Probability')
plt.title('Line Plot of Binomial Probabilities')
plt.show()

"""Histograms are used to visualized sampled data and show the shape of distribution."""

np.random.seed(0)
sample_size = 10000
sample_means = np.random.binomial(sample_size, 0.5, 100000) / sample_size

plt.hist(sample_means, bins='auto', edgecolor='black', density=True)
plt.xlabel('Binned Sample Mean')
plt.ylabel('Relative Likelihood')
plt.title('Histogram of Sample Means')
plt.show()

"""the main Matplotlib plots useed here are line plots and histograms line plots show probability distributions and histograms help show the distribution of many sampled results"""