# -*- coding: utf-8 -*-
"""Lab_06_Notebook_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3mkqsz7pfYsAD4MRKZyDUlO1-T-5o6v

this notebook shows how to plot coin flipping probabilities
"""

import matplotlib.pyplot as plt
from scipy import stats

"""for 20 flips the x axis is the number of heads from 0-20 the y axis is the probability of getting each head count"""

num_flips = 20
prob_head = 0.5

interval_all_counts = range(num_flips + 1)
probabilities = stats.binom.pmf(interval_all_counts, num_flips, prob_head)

plt.plot(interval_all_counts, probabilities)
plt.xlabel('Head-count')
plt.ylabel('Probability')
plt.title('Probability Distribution for 20 Coin Flips')
plt.show()

"""the chapter also talks about plotting many distributions at once to compare how they change as the number of flips increases."""

flip_counts = [20, 80, 140, 200]
linestyles = ['-', '--', '-.', ':']
colors = ['b', 'g', 'r', 'k']

for num_flips, linestyle, color in zip(flip_counts, linestyles, colors):
    x_values = range(num_flips + 1)
    y_values = stats.binom.pmf(x_values, num_flips, 0.5)
    plt.plot(x_values, y_values, linestyle=linestyle, color=color, label=f'{num_flips} coin-flips')

plt.legend()
plt.xlabel('Head-count')
plt.ylabel('Probability')
plt.title('Coin-Flip Probability Distributions')
plt.show()

"""the chapter also talks about the exact probability of one head count and the probability of an extreme result."""

num_heads = 16
num_flips = 20
prob_head = 0.5

prob_exact_16 = stats.binom.pmf(num_heads, num_flips, prob_head)
prob_extreme = stats.binom_test(num_heads, num_flips, prob_head)

print("Probability of exactly 16 heads:", prob_exact_16)
print("Probability of 16 or more heads or 16 or more tails:", prob_extreme)