# -*- coding: utf-8 -*-
"""Lab_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yGe6FYGMGA8_aT7z9_TH0Lzv2XKXKRc6

1. (a) define a sample space for a fair, unbiased coin;
"""

sample_space = {'Heads','Tails'}

"""1. (b) Define a weighted sample space for a biased coin that generates tails three times more often than heads."""

Weighted_sample_space = {'Tails': 3 'Heads': 1}

"""1(c) Write a function compute_event_probability that calculates the probability of each elementary event.

"""

for event_condition in event_conditions:
  prob = compute_event_probability(event_condition, weighted_sample_space)
  name = event_condition.__name__
  print(f"Probability of event arising from '{name}' is {prob}")

"""2. you have four coins, each is equaly likely to be heads or tails, what is the chance the set is balanced (i.e., two heads and two tails)?)."""

def is_balenced(outcome):
  return len([coin for coin in outcome if coin == "Heads"]) == 2
  prob = compute_event_probability(is_balenced, sample_space)
  print(f"Probability of two heads is {prob}")

"""3. Suppose we're shown a fair six-sided die whose faces are numbered from 1 to 6. The die is rolled eight times. What is the probability that these eight die rolls add up to 28?"""

def has_sum_of_28(outcome):
  return sum(outcome) == 28
prob = compute_event_probability(has_sum_of_28)
print(f"8 rolls sum to 28 with a probability of {prob}")

"""4.Write code that will compute the likelihood that our eight consecutive die rolls sum to a value between 14 and 24 inclusive."""

def is_in_interval(number, minimum, maximum):
  return minimum <= number <= maximum

prob = compute_event_probability(lambda x: is_in_interval(sum(x), 14, 24), weighted_sample_space)
print(f"Probability of interval is {prob}")

"""5. write code that finds out the probability that the coin flips do not produce from 3 to 7 heads."""

def is_in_interval(number, minimum, maximum):
  return minimum <= number <= maximum
prob = compute_event_probability(lambda x: not is_in_interval(x, 3, 7), sample_space)
print(f"Probability of heads is {prob}")

"""Now determine the probability of 20 fair coin fips not producing from 5 to 15 heads (or tails)

"""

def is_in_interval(number, minimum, maximum):
  return minimum <= number <= maximum
prob = compute_event_probability(lambda x: not is_in_interval(x, 5, 15), weighted_sample_space)
print(f"Probability of heads is {prob}")

"""What does the book say about Chapter 2?
In the subsequent section, we discuss Matplotlib usage and its application to probability theory.  

"""