# -*- coding: utf-8 -*-
"""Lab_06_Notebook_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13nWF7bJmxeF_o_msKWJRszK8cvxkj2TK

Why does the probability of observing an extreme result decrease as the coin is flipped more times? as the number of flips oncreases, the distribution becomes centered around half the flips and extreme outcomes move farther into the tails of the distribution, that makes the extreme results less likely relative to the full distribution
"""

import matplotlib.pyplot as plt
from scipy import stats

"""we compare distributions for 20, 80, 140, and 200 flips"""

flip_counts = [20, 80, 140, 200]
linestyles = ['-', '--', '-.', ':']
colors = ['b', 'g', 'r', 'k']

for num_flips, linestyle, color in zip(flip_counts, linestyles, colors):
    x_values = range(num_flips + 1)
    y_values = stats.binom.pmf(x_values, num_flips, 0.5)
    plt.plot(x_values, y_values, linestyle=linestyle, color=color, label=f'{num_flips} coin-flips')

plt.legend()
plt.xlabel('Head-count')
plt.ylabel('Probability')
plt.title('Why Extreme Results Become Less Likely')
plt.show()

"""next you compare an extreme result across flip counts"""

prob_16_of_20 = stats.binom_test(16, 20, 0.5)
prob_64_of_80 = stats.binom_test(64, 80, 0.5)
prob_112_of_140 = stats.binom_test(112, 140, 0.5)
prob_160_of_200 = stats.binom_test(160, 200, 0.5)

print("Probability of extreme result with 20 flips:", prob_16_of_20)
print("Probability of extreme result with 80 flips:", prob_64_of_80)
print("Probability of extreme result with 140 flips:", prob_112_of_140)
print("Probability of extreme result with 200 flips:", prob_160_of_200)

"""the more we flip the coin the mean and variance increase the average number of heads is around half the total flips so the center of the distribution keeps moving to the right as you flip more times"""

means = [stats.binom.mean(n, 0.5) for n in range(1, 201)]
variances = [stats.binom.var(n, 0.5) for n in range(1, 201)]

plt.plot(range(1, 201), means, label='Mean')
plt.plot(range(1, 201), variances, label='Variance')
plt.xlabel('Coin Flips')
plt.ylabel('Value')
plt.title('Mean and Variance as Flip Count Increases')
plt.legend()
plt.show()

"""Matplotlib helps by making the binomial distributions visible"""